// Auto-generated by scripts/export_test_feature.py — do not edit manually.
// scipy.signal.savgol_coeffs(width=9, polyorder=N, deriv=N), REVERSED so
// the MCU can apply it as result[t] = sum_n kernel[n+half] * x[t+n].
//
// Edge handling: polyorder == deriv ⇒ highest-order derivative is constant
// across the fitted polynomial, so boundary frames inherit the value of the
// nearest interior frame (which is exactly what scipy mode='interp' yields).
#pragma once

constexpr int kDeltaWidth = 9;
constexpr int kDeltaHalf  = 4;

constexpr float kDelta1Kernel[9] = {-6.6666670e-02f, -5.0000001e-02f, -3.3333335e-02f, -1.6666668e-02f, -9.2518590e-19f, 1.6666668e-02f, 3.3333335e-02f, 5.0000001e-02f, 6.6666670e-02f};

constexpr float kDelta2Kernel[9] = {6.0606062e-02f, 1.5151516e-02f, -1.7316017e-02f, -3.6796536e-02f, -4.3290045e-02f, -3.6796536e-02f, -1.7316017e-02f, 1.5151516e-02f, 6.0606062e-02f};
