#pragma once

// Generated by scripts/convert.py after training.
// Run: python scripts/convert.py model/ds_cnn_a0.75_int8.tflite
extern const unsigned char g_model_data[];
extern const unsigned int  g_model_data_len;
