"""
convert.py — Convert a .tflite model to a C array + export feature normalization params.

Usage:
  python scripts/convert.py [path/to/model.tflite] [array_name]

Defaults:
  tflite  → model/ds_cnn_a0.25_int8.tflite
  name    → g_model_data

Outputs:
  model/model_data.cc                  — byte array (reference copy)
  firmware/src/model_data.cc           — copy compiled into firmware
  firmware/include/norm_params.h       — kFeatMean/kFeatStd from norm_stats.npz
                                         (log-mel 40 + Δ + ΔΔ = 120 dims)
"""

import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent

DEFAULT_TFLITE = ROOT / "model" / "ds_cnn_a0.25_int8.tflite"
CC_MODEL_COPY  = ROOT / "model"    / "model_data.cc"
FW_MODEL_OUT   = ROOT / "firmware" / "src"     / "model_data.cc"
FW_NORM_OUT    = ROOT / "firmware" / "include" / "norm_params.h"
NORM_PATH      = ROOT / "model" / "norm_stats.npz"


def tflite_to_cc(data: bytes, array_name: str) -> str:
    hex_vals = [f"  0x{b:02x}" for b in data]
    rows = [", ".join(hex_vals[i:i+12]) for i in range(0, len(hex_vals), 12)]
    return (
        "// Auto-generated by scripts/convert.py — do not edit manually.\n"
        f"// TFLite flatbuffer: {len(data):,} bytes\n"
        '#include "model_data.h"\n\n'
        f"alignas(8) const unsigned char {array_name}[] = {{\n"
        + ",\n".join(rows) + "\n"
        "};\n"
        f"const unsigned int {array_name}_len = {len(data)}u;\n"
    )


def export_norm_params() -> str:
    if not NORM_PATH.exists():
        raise SystemExit(
            f"[ERR] {NORM_PATH} not found — run scripts/compress_sweep.py first."
        )
    d        = np.load(str(NORM_PATH))
    mean     = np.squeeze(d["mean"]).astype(np.float64)   # (n_feat,)
    std      = np.squeeze(d["std"]).astype(np.float64)
    n_feat   = mean.shape[0]
    print(f"[INFO] feature norm params: {n_feat} dims  "
          f"(mean range [{mean.min():.3f}, {mean.max():.3f}], "
          f"std range [{std.min():.3f}, {std.max():.3f}])")

    def arr(vals):
        return ",\n    ".join(f"{v:.8f}f" for v in vals)

    return (
        "// Auto-generated by scripts/convert.py — do not edit manually.\n"
        "// Per-coefficient z-score statistics from training set.\n"
        "// Features: log-mel (40) + delta + delta-delta = 120 dims.\n"
        "#pragma once\n\n"
        f"constexpr int   kFeatDim         = {n_feat};\n\n"
        f"constexpr float kFeatMean[{n_feat}] = {{\n    {arr(mean.tolist())},\n}};\n\n"
        f"constexpr float kFeatStd[{n_feat}]  = {{\n    {arr(std.tolist())},\n}};\n"
    )


def main():
    tflite_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_TFLITE
    array_name  = sys.argv[2]       if len(sys.argv) > 2 else "g_model_data"

    if not tflite_path.exists():
        raise SystemExit(f"[ERR] {tflite_path} not found")

    data   = tflite_path.read_bytes()
    cc_src = tflite_to_cc(data, array_name)

    for out in (CC_MODEL_COPY, FW_MODEL_OUT):
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(cc_src)
        print(f"[INFO] {len(data):,} bytes → {out}")

    FW_NORM_OUT.parent.mkdir(parents=True, exist_ok=True)
    FW_NORM_OUT.write_text(export_norm_params())
    print(f"[INFO] norm params → {FW_NORM_OUT}")


if __name__ == "__main__":
    main()
