"""export_test_feature.py — emit firmware-side test fixtures.

For one deterministic clip from the test set, write:
  model/test_audio.bin                   raw int16 PCM (32000 bytes)
  model/expected_feature.bin             quantized int8 features (7320 bytes)
  model/test_metadata.json               provenance + quant params
  firmware/include/mel_filterbank.h      librosa Slaney mel matrix (40 × 257)
  firmware/include/delta_kernels.h       scipy savgol kernels (9 taps each)
  firmware/include/test_data.h           audio + expected features as C arrays
                                          (so the FEATURE_TEST build needs no LittleFS upload)

The expected features run through the same pipeline as preprocess.py BUT start
from `int16 / 32768`, not the original float — that matches what the MCU mic
actually delivers, so the test exercises bit-exact MCU↔Python parity.
"""
import json
from pathlib import Path

import librosa
import numpy as np
import tensorflow as tf
from scipy.signal import savgol_coeffs

ROOT      = Path(__file__).resolve().parent.parent
MODEL     = ROOT / "model" / "sweep_a1.0_int8.tflite"
NORM      = ROOT / "model" / "norm_stats.npz"
TEST_DIR  = ROOT / "data" / "bark" / "dog_bark_test"
TEST_WAV  = sorted(TEST_DIR.glob("*.wav"))[0]   # first by name — deterministic
CLASSES   = ["bark", "growl", "grunt", "ambient"]

SR, CLIP        = 16_000, 16_000
N_FFT, HOP      = 512, 256
N_MELS          = 40
DELTA_WIDTH     = 9
TARGET_DBFS     = -3.0


# ── 1. Pick + condition a deterministic test clip ─────────────────────────────
print(f"[1] loading {TEST_WAV.relative_to(ROOT)}")
y, _ = librosa.load(str(TEST_WAV), sr=SR, mono=True)

# Trim silence + center-pad to 1 s (matches preprocess.py trim_and_window)
y_trim, _ = librosa.effects.trim(y, top_db=30.0)
if len(y_trim) < CLIP:
    pad = CLIP - len(y_trim)
    seg = np.pad(y_trim, (pad // 2, pad - pad // 2))
else:
    seg = y_trim[:CLIP]

# Peak-normalize to -3 dBFS to match preprocess.py
peak = float(np.max(np.abs(seg)))
seg  = seg * (10 ** (TARGET_DBFS / 20.0) / peak) if peak > 1e-9 else seg

# Convert to int16 — this is what the PDM mic feeds the MCU
seg_i16 = np.clip(seg * 32767.0, -32768, 32767).astype(np.int16)

audio_bin = ROOT / "model" / "test_audio.bin"
audio_bin.write_bytes(seg_i16.tobytes())
print(f"    wrote {audio_bin.relative_to(ROOT)}  ({audio_bin.stat().st_size} bytes)")


# ── 2. Run feature pipeline on the int16-roundtripped float ───────────────────
print(f"[2] computing reference features")
seg_f = seg_i16.astype(np.float32) / 32768.0

mel    = librosa.feature.melspectrogram(
    y=seg_f, sr=SR, n_fft=N_FFT, hop_length=HOP, n_mels=N_MELS, center=False)
logmel = librosa.power_to_db(mel, ref=np.max).astype(np.float32)         # (40, 61)
d1     = librosa.feature.delta(logmel, width=DELTA_WIDTH, order=1).astype(np.float32)
d2     = librosa.feature.delta(logmel, width=DELTA_WIDTH, order=2).astype(np.float32)
feat   = np.concatenate([logmel, d1, d2], axis=0)                        # (120, 61)
print(f"    feature shape {feat.shape}  range [{feat.min():.2f}, {feat.max():.2f}]")


# ── 3. Z-score with training stats, then quantize to model input ───────────────
print(f"[3] z-score + INT8 quantize")
norm  = np.load(NORM)
mean  = np.squeeze(norm["mean"]).astype(np.float32)                       # (120,)
std   = np.squeeze(norm["std"]).astype(np.float32)
feat  = (feat - mean[:, None]) / std[:, None]

interp = tf.lite.Interpreter(model_path=str(MODEL))
interp.allocate_tensors()
inp_d, out_d = interp.get_input_details()[0], interp.get_output_details()[0]
scale, zp = inp_d["quantization"]

q = np.clip(np.rint(feat / scale + zp), -128, 127).astype(np.int8)        # (120, 61)
expected_bin = ROOT / "model" / "expected_feature.bin"
expected_bin.write_bytes(q.tobytes())
print(f"    wrote {expected_bin.relative_to(ROOT)}  ({expected_bin.stat().st_size} bytes)")
print(f"    quant: scale={scale:.6f} zero_point={zp}  q range [{q.min()}, {q.max()}]")


# ── 4. Verify the quantized fixture still classifies correctly ────────────────
print(f"[4] running model on fixture to sanity-check class")
x_in = q[np.newaxis, :, :, np.newaxis]   # (1, 120, 61, 1)
interp.set_tensor(inp_d["index"], x_in)
interp.invoke()
out  = interp.get_tensor(out_d["index"])[0]
pred = int(np.argmax(out))
print(f"    predicted class: {pred} = {CLASSES[pred]}   (raw output {out.tolist()})")


# ── 5. Mel filterbank header ──────────────────────────────────────────────────
print(f"[5] writing mel_filterbank.h")
mel_basis = librosa.filters.mel(
    sr=SR, n_fft=N_FFT, n_mels=N_MELS, htk=False).astype(np.float32)      # (40, 257)
N_BINS = N_FFT // 2 + 1
mel_h  = ROOT / "firmware" / "include" / "mel_filterbank.h"

lines = [
    "// Auto-generated by scripts/export_test_feature.py — do not edit manually.",
    "// librosa.filters.mel(sr=16000, n_fft=512, n_mels=40, htk=False, norm='slaney')",
    "#pragma once",
    "",
    f"constexpr int kMelBins = {N_MELS};",
    f"constexpr int kFftBins = {N_BINS};",
    "",
    f"constexpr float kMelFb[{N_MELS}][{N_BINS}] = {{",
]
for m in range(N_MELS):
    row = ", ".join(f"{v:.7e}f" for v in mel_basis[m])
    lines.append(f"  {{{row}}},")
lines.append("};\n")
mel_h.write_text("\n".join(lines))
print(f"    {mel_h.relative_to(ROOT)}  ({mel_h.stat().st_size} bytes)")


# ── 6. Savgol delta kernels header ────────────────────────────────────────────
print(f"[6] writing delta_kernels.h")
# scipy savgol_filter uses a *flipped* convention internally: result[t] is
# sum_i k[i] * x[t + half - i]. Reverse here so the MCU can apply the kernel
# in the natural ordering: result[t] = sum_n k_rev[n + half] * x[t + n].
d1_k = savgol_coeffs(DELTA_WIDTH, polyorder=1, deriv=1)[::-1].astype(np.float32)
d2_k = savgol_coeffs(DELTA_WIDTH, polyorder=2, deriv=2)[::-1].astype(np.float32)
dk_h = ROOT / "firmware" / "include" / "delta_kernels.h"

dk_h.write_text(
    "// Auto-generated by scripts/export_test_feature.py — do not edit manually.\n"
    "// scipy.signal.savgol_coeffs(width=9, polyorder=N, deriv=N), REVERSED so\n"
    "// the MCU can apply it as result[t] = sum_n kernel[n+half] * x[t+n].\n"
    "//\n"
    "// Edge handling: polyorder == deriv ⇒ highest-order derivative is constant\n"
    "// across the fitted polynomial, so boundary frames inherit the value of the\n"
    "// nearest interior frame (which is exactly what scipy mode='interp' yields).\n"
    "#pragma once\n\n"
    f"constexpr int kDeltaWidth = {DELTA_WIDTH};\n"
    f"constexpr int kDeltaHalf  = {DELTA_WIDTH // 2};\n\n"
    f"constexpr float kDelta1Kernel[{DELTA_WIDTH}] = {{"
    + ", ".join(f"{v:.7e}f" for v in d1_k) + "};\n\n"
    f"constexpr float kDelta2Kernel[{DELTA_WIDTH}] = {{"
    + ", ".join(f"{v:.7e}f" for v in d2_k) + "};\n"
)
print(f"    {dk_h.relative_to(ROOT)}  ({dk_h.stat().st_size} bytes)")


# ── 7. Test fixture as C arrays (no LittleFS upload required) ─────────────────
print(f"[7] writing test_data.h")
test_h = ROOT / "firmware" / "include" / "test_data.h"

def fmt_chunks(values, per_line, fmt):
    out = []
    for i in range(0, len(values), per_line):
        out.append("  " + ",".join(fmt.format(v) for v in values[i:i+per_line]) + ",")
    return "\n".join(out)

flat_q = q.flatten()
test_h.write_text(
    "// Auto-generated by scripts/export_test_feature.py — do not edit manually.\n"
    "// Test fixture: int16 PCM audio + expected int8 quantized features.\n"
    "// Compiled in only when -DFEATURE_TEST is set; otherwise unused.\n"
    "#pragma once\n#include <cstdint>\n\n"
    f"// Source: {TEST_WAV.relative_to(ROOT)}\n"
    f"// Expected class: {pred} ({CLASSES[pred]})\n"
    f"constexpr int     kTestAudioLen        = {seg_i16.size};\n"
    f"constexpr int16_t kTestAudio[{seg_i16.size}] = {{\n"
    + fmt_chunks(seg_i16.tolist(), per_line=12, fmt="{:d}")
    + "\n};\n\n"
    f"constexpr int    kExpectedFeatureLen = {flat_q.size};\n"
    f"constexpr int8_t kExpectedFeature[{flat_q.size}] = {{\n"
    + fmt_chunks(flat_q.tolist(), per_line=20, fmt="{:d}")
    + "\n};\n\n"
    f"constexpr int8_t kTestExpectedClass = {pred};\n"
)
print(f"    {test_h.relative_to(ROOT)}  ({test_h.stat().st_size} bytes)")


# ── 8. Metadata ───────────────────────────────────────────────────────────────
meta = {
    "source_wav":         str(TEST_WAV.relative_to(ROOT)),
    "expected_class":     pred,
    "expected_class_name": CLASSES[pred],
    "input_scale":        float(scale),
    "input_zero_point":   int(zp),
    "n_frames":           int(q.shape[1]),
    "feat_dim":           int(q.shape[0]),
    "feat_value_range":   [int(q.min()), int(q.max())],
}
meta_path = ROOT / "model" / "test_metadata.json"
meta_path.write_text(json.dumps(meta, indent=2))
print(f"\n[done] metadata → {meta_path.relative_to(ROOT)}")
print(f"\nNext: flash with `-DFEATURE_TEST` (uncomment in platformio.ini) to verify on-chip.")
